# Generated by Django 2.1.5 on 2019-06-13 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.CharField(help_text='enter a unique id for this particular book', max_length=20, primary_key=True, serialize=False),
        ),
    ]
