# Generated by Django 2.1.5 on 2019-07-08 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20190613_1006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinstance',
            old_name='due_date',
            new_name='issued_on',
        ),
    ]
